# coding: utf-8

"""
    API de Cours

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.recherche_de_cours_api import RechercheDeCoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRechercheDeCoursApi(unittest.TestCase):
    """RechercheDeCoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.recherche_de_cours_api.RechercheDeCoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_tag_get(self):
        """Test case for search_tag_get

        Recherche de cours par tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
