# coding: utf-8

"""
    API de Cours

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cours_api import CoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCoursApi(unittest.TestCase):
    """CoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cours_api.CoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cours_id_delete(self):
        """Test case for cours_id_delete

        Supprime un cours  # noqa: E501
        """
        pass

    def test_cours_id_get(self):
        """Test case for cours_id_get

        Retourne les informations du cours  # noqa: E501
        """
        pass

    def test_cours_id_post(self):
        """Test case for cours_id_post

        Crée un nouveau cours  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
