# coding: utf-8

"""
    API de Cours

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sances_api import SancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSancesApi(unittest.TestCase):
    """SancesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sances_api.SancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cours_seances_id_delete(self):
        """Test case for cours_seances_id_delete

        Supprime une séance  # noqa: E501
        """
        pass

    def test_cours_seances_id_get(self):
        """Test case for cours_seances_id_get

        Retourne les infos sur la séance  # noqa: E501
        """
        pass

    def test_cours_seances_id_post(self):
        """Test case for cours_seances_id_post

        Crée une nouvelle séance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
