# coding: utf-8

"""
    API de Cours

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contenu_de_cours_api import ContenuDeCoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContenuDeCoursApi(unittest.TestCase):
    """ContenuDeCoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.contenu_de_cours_api.ContenuDeCoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cours_id_dossier_delete(self):
        """Test case for cours_id_dossier_delete

        Supprime un dossier du cours  # noqa: E501
        """
        pass

    def test_cours_id_dossier_get(self):
        """Test case for cours_id_dossier_get

        Retourne un JSON du contenu du dossier  # noqa: E501
        """
        pass

    def test_cours_id_dossier_post(self):
        """Test case for cours_id_dossier_post

        Crée un nouveau dossier pour le cours  # noqa: E501
        """
        pass

    def test_cours_id_fichier_delete(self):
        """Test case for cours_id_fichier_delete

        Supprime un fichier du cours  # noqa: E501
        """
        pass

    def test_cours_id_fichier_get(self):
        """Test case for cours_id_fichier_get

        Retourne un fichier selon le chemin spécifié  # noqa: E501
        """
        pass

    def test_cours_id_fichier_post(self):
        """Test case for cours_id_fichier_post

        Télécharge un fichier pour le cours  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
