# coding: utf-8

# flake8: noqa

"""
    API de Cours

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.contenu_de_cours_api import ContenuDeCoursApi
from swagger_client.api.cours_api import CoursApi
from swagger_client.api.recherche_de_cours_api import RechercheDeCoursApi
from swagger_client.api.sances_api import SancesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
